### ISSUE TITLE
Change Plugin admin list upgrade behaviour

### ISSUE THREAD

**Issue by morbac** [notepad-plus-plus/nppPluginList#199]
As fas as I know, the Plugin admin list is updated with new NPP releases. This slows down reactivness in plugins bug fix.

For instance, the actual most recent release of NPP is 7.8.5, published one month and a half ago. Just after NPP release, I found a bug in my plugin which slowed down search/replace functions in NPP. I fixed it a few days later but it's still not available for users through Plugin admin since no new NPP version has been released in the meanwhile.

It would be nice if Plugin admin list could be updated faster than NPP upgrades.

**Comment by chcg** [comment]
This was discussed and probably is a feature which needs to be implemented by https://github.com/notepad-plus-plus/wingup.

**Comment by donho** [comment]
The plugin list update being independent of Notepad++ release was planned from the beginning. However with the evolution of its specs it becomes difficult.

The plugin list is a binary signed by a certificate of Notepad++. It means each release will be done by me (who only have the P12 file to sign). So currently I prefer to do a plugin list release each time I release Notepad++. Since plugin list release always comes with Notepad++, the plugin list update is no more needed (which is complex process as well).

With such circumstance all I can do is try to release Notepad++ 1 time per month. It's not ideal I know. Let me know if you got a better solution.

**Comment by p0358** [comment]
> Let me know if you got a better solution.

@donho I suppose some CI script could periodically generate and sign updates, it could push them to whatever server to download too. Such a thing could probably be hosted locally too, or perhaps on something like GitHub Actions with some sub-certificate?

Then Plugins Admin could check for update once it's been opened, if enough time passed since last list update (say 1 day?). CI script could also be fired off every 1 day instead of on pushes, and only create an update if there were any commits since that time...

As for where to host, I'd say Cloudflare, either free regular service, or Cloudflare R2 (their bucket storage which has 20 million requests in free tier + free bandwidth). In worst case scenario if hosting goes down, failed update should not prevent the locally available list from being used and shipped with Notepad++ in every update same way

As for what if format of the DLL changes, that should be handled by its major version, and such versions would be hosted separately, so that old clients wouldn't get such incompatible changed format version then
