### ISSUE TITLE
validator.py issue on homepage uri

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/nppPluginList#99]
They are 18 plugins without plugin homepage (4 for x64, 14 for x86)

From plugin json format, hompage is required.
Validator.py doesn't trigger any error on appveyor however if you don't install python package rfc3987 (Parsing and validation of URIs and IRIs), error will be found.

@chc what is the desired behavior ? is homepage  mandatory ?

**Comment by dail8859** [comment]
According to the schema I created the webpage attribute must exist. It either needs to be an empty string or a valid url. I did this so that this attribute would not be accidentally missed, but also allow plugins to not be required since I knew several of the older plugins didn't specify a homepage.

That being said, I'm not saying the behavior needs kept the way it is.

**Comment by cmeriaux** [comment]
your reasoning makes sense
Let's close the issue

**Comment by chcg** [comment]
@cmeriaux a g is missing in your posting above. It should have been @chcg . As dail8859 said I would expect for new plugins to have a homepage available, but not require for older plugins. Currently it is mainly a take over from plugin manager settings.

**Comment by cmeriaux** [comment]
@chcg  Fair enough. Let's keep this issue closed
